### ISSUE TITLE
Catching a CrateDB fluke: `ShardCollectContext for {0,2} already added`

### ISSUE THREAD

**Issue by amotl** [crate-workbench/mlflow-cratedb#53]
## Report

While trying to bring in GH-52, we caught an unusual error from CrateDB we haven't seen before.
```
ShardCollectContext for 0 already added
```

It is happening on a `DELETE FROM` SQL statement.
```sql
DELETE FROM metrics;
```

## Details

The `DELETE FROM metrics` is happening within a regular integration test scenario on the canonical `setUp()` method calling out to `self.pruneTables()`, in order to supply the test cases with a blank canvas. This is nothing special, we have been doing it like this for a while already, on behalf of different test suites we are maintaining. Also note it was really only a fluke: Re-running the test cases made them succeed on the first attempt already.

-- https://github.com/crate-workbench/mlflow-cratedb/actions/runs/6721484528/job/18267317481?pr=52#step:6:491

## Thoughts

As we are using CrateDB nightly for all of our downstream integration tests, **it may be a regression introduced just recently**.

/cc @matriv, @seut

**Comment by BaurzhanSakhariev** [comment]
Hi, I don't have permissions to assign myself, will check it out.

**Comment by amotl** [comment]
Thank you. Please note that it was a single event, and it hasn't been observed ever after. Maybe a real [SEU](https://community.hiveeyes.org/t/soft-errors-caused-by-single-event-upsets-seus-aka-ecc-ram-absolutely-matters/1891)?

**Comment by BaurzhanSakhariev** [comment]
Maybe relates to https://github.com/crate/crate/issues/11677

**Comment by amotl** [comment]
Another spot on behalf of GH-64.

-- https://github.com/crate-workbench/mlflow-cratedb/actions/runs/6846915144/job/18614271079?pr=64#step:6:488

**Comment by matriv** [comment]
could it be that we need to have an `ensureGreen()` alternative for this one?

**Comment by amotl** [comment]
Thank you for watching this conversation, Marios.

> could it be that we need to have an `ensureGreen()` alternative for this one?

I am not sure what you are particularly referring to with `ensureGreen()`. Up until now, I only have been able to spot this flaw twice, starting with its first occurrance two weeks ago.

**Comment by amotl** [comment]
Just to add more context here, to improve the original report: The flaw is apparently not happening on CrateDB startup, but at regular runtime.

```
tests/test_tracking.py::TestSqlAlchemyStore::test_search_runs_pagination PASSED [ 85%]
tests/test_tracking.py::TestSqlAlchemyStore::test_search_runs_returns_expected_results_with_large_experiment PASSED [ 85%]
tests/test_tracking.py::TestSqlAlchemyStore::test_search_runs_run_id FAILED [ 86%]
tests/test_tracking.py::TestSqlAlchemyStore::test_search_runs_run_name PASSED [ 87%]
tests/test_tracking.py::TestSqlAlchemyStore::test_search_runs_start_time_alias PASSED [ 88%]
```
-- https://github.com/crate-workbench/mlflow-cratedb/actions/runs/6721484528/job/18267317481?pr=52#step:6:154

```
tests/test_tracking.py::TestSqlAlchemyStore::test_search_runs_pagination PASSED [ 85%]
tests/test_tracking.py::TestSqlAlchemyStore::test_search_runs_returns_expected_results_with_large_experiment PASSED [ 86%]
tests/test_tracking.py::TestSqlAlchemyStore::test_search_runs_run_id FAILED [ 86%]
tests/test_tracking.py::TestSqlAlchemyStore::test_search_runs_run_name PASSED [ 87%]
tests/test_tracking.py::TestSqlAlchemyStore::test_search_runs_start_time_alias PASSED [ 88%]
```

-- https://github.com/crate-workbench/mlflow-cratedb/actions/runs/6846915144/job/18614271079?pr=64#step:6:488

**Comment by matriv** [comment]
> I am not sure what you are particularly referring to with `ensureGreen()`. Up until now, I only have been able to spot this flaw twice, starting with its first occurrance two weeks ago.

I'm probably wrong, I was thinking to check that all shards of a table are allocated before proceeding with statements, but we use only one cratedb node, right?

**Comment by amotl** [comment]
The output I've shared above clearly indicates that it is happenening at the very same test case function `test_search_runs_run_id`. What might be particularly more interesting in this case, is the predecessor test case function, `test_search_runs_returns_expected_results_with_large_experiment`.

This observation indicates that CrateDB might not be ready to accept a `DELETE FROM ...` statement on a database table after inserting a large amount of data [^1] into it. Do you think we are missing an additional `REFRESH TABLE ...` statement before conducting the `DELETE FROM ...`?

We can try, and it may qualify as a workaround. However, you may also want to address this on behalf of CrateDB itself, when applicable.

[^1]: Of the shape as performed by the `test_search_runs_returns_expected_results_with_large_experiment` test case function.

**Comment by amotl** [comment]
To add more information about chronology: It has first happened here at PR-52, on Wed, 01 Nov 2023, with this release:
```
version[5.6.0-SNAPSHOT], pid[1], build[827ccae/NA], OS[Linux/6.2.0-1015-azure/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/21.0.1+12-LTS]
```

The second spot was:
```
version[5.6.0-SNAPSHOT], pid[1], build[ca0a7b6/NA], OS[Linux/6.2.0-1015-azure/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/21.0.1+12-LTS]
```

Unfortunately, we didn't schedule nightly checks on this repository, so if there indeed is a flaw, it has probably been introduced way earlier.

**Comment by amotl** [comment]
It happened again, this time on a CI run triggered by a PR submitted by Dependabot.

-- https://github.com/crate-workbench/mlflow-cratedb/actions/runs/6927008529/job/18840093364?pr=68#step:6:346

**Comment by amotl** [comment]
Now, it is about `ShardCollectContext for 2` instead of `ShardCollectContext for 0`.

```
FAILED tests/test_tracking.py::TestSqlAlchemyStore::test_search_runs_run_id - mlflow.exceptions.MlflowException: (crate.client.exceptions.ProgrammingError) SQLParseException[ShardCollectContext for 2 already added]
[SQL: DELETE FROM metrics]
(Background on this error at: https://sqlalche.me/e/20/f405)
```
-- https://github.com/crate-workbench/mlflow-cratedb/actions/runs/6985231736/job/19009218790?pr=69#step:6:663

**Comment by amotl** [comment]
Once more.

-- https://github.com/crate-workbench/mlflow-cratedb/actions/runs/7375903029/job/20068020355?pr=81#step:6:907

**Comment by amotl** [comment]
Again...

-- https://github.com/crate-workbench/mlflow-cratedb/actions/runs/7710716645/job/21014632426?pr=96#step:6:1008

**Comment by amotl** [comment]
That other patch will increase CrateDB's heap size on CI, in order to explore whether the problem originates from low-memory situations.

- GH-100

**Comment by amotl** [comment]
> [...] whether the problem originates from low-memory situations.

Indeed. Decreasing heap size triggers the problem right away. In this spirit, creating a reproducer will be much easier.

```console
docker run --rm -it --name=cratedb \
  --publish=4200:4200 --publish=5432:5432 \
  --env=CRATE_HEAP_SIZE=256m \
  crate/crate:nightly -Cdiscovery.type=single-node
```
```console
time pytest -vvv -k "test_search_runs_returns_expected_results_with_large_experiment or test_search_runs_run_id"
```

**Comment by amotl** [comment]
The issue has been reported to the upstream crate/crate repository.

- https://github.com/crate/crate/issues/15518

**Comment by amotl** [comment]
Coming from https://github.com/crate/crate/issues/15518#issuecomment-1943985644, and looking at recent nightly scheduled job executions of https://github.com/crate-workbench/mlflow-cratedb/actions, it looks like this problem has been mitigated. Therefore, I am closing this.

Thanks, @jeeminso.
